services:
  app:
    build: ../
    restart: always
    ports:
     - 8000:8000
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles
    depends_on:
      - app

  db:
    image: postgres:13-alpine
    ports:
      - :5432
    env_file: .env
    volumes:
      - db_postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d hb_project_db -U postgres_userhb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_postgresql:
  static: